version: "3"
services:
  frontend:
    build: .
    container_name: frontend
    environment:
      NEXT_PUBLIC_CALLBACK_TOKEN: ${NEXT_PUBLIC_CALLBACK_TOKEN}

  nginx:
    build:
      context: ./nginx # Build the NGINX image from the nginx folder
    container_name: nginx
    ports:
      - "5080:80" # Expose 5080 on the host and map to 80 in the container
    depends_on:
      - frontend
