version: "3"
services:
  frontend:
    build: .
    container_name: frontend
    environment:
      NEXT_PUBLIC_CALLBACK_TOKEN: ${NEXT_PUBLIC_CALLBACK_TOKEN}

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
