import { Toaster } from '@/components/ui/toaster'
import { getLocale } from '@/i18n/i18n-server.config'
import { LocaleProvider } from '@/providers/locale.provider'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserratSans = Montserrat({
	variable: '--font-montserrat-sans',
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const locale = await getLocale()

	return (
		<html lang={locale}>
			<body className={`${montserratSans.variable}  antialiased`}>
				<LocaleProvider value={locale}>
					<Toaster />
					{children}
				</LocaleProvider>
			</body>
		</html>
	)
}
